### PR TITLE
allow to right click on the entire root area

### PR DESCRIPTION
**Pull request by Lyqed**
Add ability to right click to create anywhere in the root area as 
image

### CODE REVIEW

**Comment by mnaoumov** [comment]
@Lyqed 
Your PR adds `dist` and `node_modules` and no typescript files changed. Please remake it

**Comment by Lyqed** [comment]
Hi. Done. @mnaoumov

**Comment by 3C0D** [comment]
you can find this  feature in https://github.com/3C0D/obsidian-explorer-shortcuts

**Comment by Lyqed** [comment]
> you can find this feature in https://github.com/3C0D/obsidian-explorer-shortcuts

Hi, I tried downloading and using your plugin, but upon right clicking on the root area, it does now show any context menu and no option to create new files or folders.

**Comment by 3C0D** [comment]
First it's a desktop plugin. Maybe it is not your case ?
There are some shortcuts working just hovering files or folders.  f new folder n new file. c, x, v, r/f2 arrows... You can press h for help and have all shortcuts. f,n are working over the nav container too...
The readme explains it well.

**Comment by Lyqed** [comment]
> First it's a desktop plugin. Maybe it is not your case ? There are some shortcuts working just hovering files or folders. f new folder n new file. c, x, v, r/f2 arrows... You can press h for help and have all shortcuts. f,n are working over the nav container too... The readme explains it well.

Hi, please look again at what my PR  adds, This is completely different from your plugin. You can see in the image that it adds two new entries in the context menu, that werent there before (in fact there was no context menu at all) when clicking anywhere in the root folder area.

Cheers.

**Comment by mnaoumov** [comment]
Thanks for your PR.

Inspired by it, I add a full menu in https://github.com/mnaoumov/obsidian-root-folder-context-menu/releases/tag/1.3.0

**Comment by 3C0D** [comment]
I used your script in a personal plugin. Well, all my plugins are not published now. Let's say I ejected myself from the official process...
https://github.com/3C0D/obsidian-tools/blob/master/src/vaultContextMenu.ts

**Comment by Lyqed** [comment]
@mnaoumov 

its probably a good idea to remove these too, just to tidy it up a little!

image

**Pull request closed without merging**
